# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd9267a4e5607715e17b8325ea838cbe5066834446cff4dc0ce32dc4152dc9d8a94b28b895ac4a173627daf88dbce3f1c1551951935e5d21f6f2c7e5490d330

test:
  secret_key_base: 209dae1eb8f28a0443af70ee8f21e4623fa463f184579e60c185d6170032e98c8755103ce5312dd9e138e703c173cef1e9363337072f57c8bc55635e38f11f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
